name: Streamlit App CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-glx libglib2.0-0
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Check app syntax
      run: |
        python -m py_compile app.py
        python -m py_compile config.py
        python -m py_compile src/tactile_converter.py
    
    - name: Test app startup
      run: |
        # Test if the app can be imported without errors
        python -c "import streamlit; import app"
    
  docker:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Docker image
      run: |
        docker build -t tactile-graphics .
    
    - name: Test Docker image
      run: |
        # Start container in background
        docker run -d -p 8501:8501 --name test-app tactile-graphics
        
        # Wait for app to start
        sleep 10
        
        # Check if the app is responding
        curl -f http://localhost:8501/_stcore/health || exit 1
        
        # Cleanup
        docker stop test-app
        docker rm test-app
